### ISSUE TITLE
Template Restructurization

### ISSUE THREAD

**Issue by adios113** [adios113/blackwatchint#29]
Total template folder and scripts restructurization.

**Comment by ShiFoo** [comment]
First version of new templates done. Pending review by aDi.
Every map already has new template structure.
[BWI]Template_v2.vr is master preset.

- Streamlined loadouts (ARs now have 3 belts + 1 tracer belt, added missing binocs)
- Extracted common items into functions
- Higher maintainability due to redundancy reduction
- BWI_fnc_AddGear and BWI_fnc_AddMedical should be used to define faction-independent loadouts.
- Loadout bug fixes
- etc

http://www8.zippyshare.com/v/dgeqATeB/file.html

**Comment by ShiFoo** [comment]
Updated version of new Template structure:

- Reflecting issues that came up in the meantime (UK AT, Nimitz teleporter (just disabled), etc. )
- Minor bugs from previous version fixed
- All Nimitz teleports fixed
- Created small Windows batch script to deploy changes from the master preset ([BWI]Template_v2.vr\BWI) into other maps. Map specific files remain unchanged. Searches map folders with [BWI] prefix (except master preset). Log files of copy process are stored in "logs" subdirectory.

- Make changes in [BWI]Template_v2.vr
- double click deploy.bat to copy changes into other maps (affects everything inside BWI\ folder except carrier_tp.sqf)

http://www64.zippyshare.com/v/keRQ0bHJ/file.html

**Comment by ShiFoo** [comment]
Updated version of new Template structure (only master template for now, until we agree on this):

- Due to aDi's experience and information of limited quality from the internet, loadouts are loaded the following way:
-- loadout sqf's are using _unit instead of player, _unit = (_this select 1); , check for locality
-- unit init lines are back to call compile preprocessFile
-- parameter for loadout script is an array with two elements (compatability mode for the pedestals to avoid having dupicate loadout scripts, also the reason to use (_this select 1) ). First element can be ignored, second element is the unit object
-- init line calls loadout scripts with [objNull, this] to avoid using player
-- pedastals are using the parameters by design according to https://community.bistudio.com/wiki/addAction
>Parameters array passed to the script upon activation in _this variable is: [target, caller, ID, arguments]
>target (_this select 0): Object - the object which the action is assigned to
>*caller (_this select 1): Object - the unit that activated the action*
>ID (_this select 2): Number - ID of the activated action (same as ID returned by addAction)
>arguments (_this select 3): Anything - arguments given to the script if you are using the extended syntax

- Zeus slots have addition actions on the SpawnVAS:
-- End Mission (Success)
-- End Mission (Failure)
-- Implemented "Reclaim AI Ownership" script as action on the VAS for convenience
- To keep this actions hidden from normal slots and to handle correct removal of those action again when reslotting between Zeus and normal, the script onPlayerRespawn.sqf handles these actions.
https://community.bistudio.com/wiki/Event_Scripts

I have tested all of this on the dedicated server and it worked.

http://www50.zippyshare.com/v/uyMhaOgE/file.html
