### ISSUE TITLE
MSKE - 4 Island map

### ISSUE THREAD

**Issue by adios113** [adios113/blackwatchint#40]
**Description:** This mod adds a one bigger map including all 4 islands known from original Operation Flashpoint Server - Malden; Sarugao; Kolgujev; Everon

https://forums.bistudio.com/topic/179117-mske-4-islands-map/

**Download:** http://www.armaholic.com/page.php?id=28299

**Comment by ShiFoo** [comment]
The screenshots of MSKE provided with the links were already quite promising. And after loading into the map, they are certainly confirmed.
All 4 islands have kind of the same setting but are still individual in their own way. One has more hills and valleys, another one is rather flat. structure-wise the north-eastern island has whole different feeling to it because of its special outline and narrow passages.
I didn't do any additional screenshots because the ones from the armaholic site are already showing the quality of the map. Rich details and a good mixture of infrastructure, buildings and forests make all four islands very appealing. 
Even though every island itself is very well done, especially cross-island ops could be interesting.

MSKE would be interesting to play. In my opinion it is good enough to be added to our mappool.

**Comment by adios113** [comment]
I've spent like 2 hours traveling around this map, doing a lot of screenshots, while testing some other stuff simultaneously. Having four bigger islands on a one map without any bigger performance drops is hard to achieve, but the map author made it and in my opinion those 4 are very beautiful islands, providing variety in terms of terrain on a one map. 

http://steamcommunity.com/id/adiospl93/screenshots

Last 120 screenshots.
