### ISSUE TITLE
Corpsmen don't have PAKs

### ISSUE THREAD

**Issue by ShiFoo** [adios113/blackwatchint#57]
Corpsmen are lacking PAKs. Needs to be added to BWI_fnc_AddMedical until ACE fixes this

**Comment by TheGrandVizier** [comment]
I know this may be silly but, since we wont be using PAKs in the future, once ACE 3.4.0 is out, wont this need to be undone anyways?
Seems to me like a duplication of effort. Might as well leave it this way and have corpsman take PAKs manually, as they do right now anyways (because 5-6 are not enough, ever). So the time is already spent in arsenal anyways.

2 cents.

**Comment by ShiFoo** [comment]
Do we have an estimate release date for the new ACE version? I know it has to be undone, but i look at the current state of the template and the mod. And then, objectively speaking, its a template bug.

**Comment by TheGrandVizier** [comment]
Talked to adi, didnt realize its automated already.
Also, yea, technically you are right, i was just trying to be witty in
terms of harnessing the bug in our favor, sort of.
Some fremen shit.
:)

**Comment by ShiFoo** [comment]
Change committed to master

**Comment by adios113** [comment]
The thing is, that i dont remember a discussion in which somebody said, that pak's should be removed from the loadouts.  It was planned yes, but after the Ace update.

**Comment by ShiFoo** [comment]
I forgot to add them to the revised template structure. Simple...

**Comment by ShiFoo** [comment]
Fix commited to master and merged to BWI_2.0
